name: Go Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.11'
        
    - name: Verify dependencies
      run: go mod verify
      
    - name: Build
      run: go build -v ./...
      
    - name: Run vet
      run: go vet ./...
      
    - name: Run unit tests
      run: go test -tags unittest -v ./...
      
    - name: Run integration tests
      run: go test -tags integtest -v ./...
